/* 8 */
SELECT `NUM_EMPLEADO` FROM empleados WHERE COMISION > (`SALARIO`/2);

/* 9 */
SELECT `NUM_EMPLEADO` FROM empleados WHERE COMISION <= (0.25 * `SALARIO`);

/* 10 */
SELECT CONCAT('Nombre ', `NOMBRE_EMPLEADO`, ' Puesto ',`PUESTO`) AS Empleado FROM empleados;

/* 11 */
SELECT `SALARIO`, `COMISION` FROM empleados WHERE `NUM_EMPLEADO` > 7500;

/* 12 */
SELECT `NOMBRE_EMPLEADO`, `PUESTO` FROM empleados WHERE NOMBRE_EMPLEADO LIKE 'J%' ORDER BY `NOMBRE_EMPLEADO`, `PUESTO`;

/* 13 */
SELECT SALARIO, COMISION, SALARIO+COMISION AS "SALARIO TOTAL" FROM empleados WHERE COMISION IS NOT NULL ORDER BY NUM_EMPLEADO;

/* 14 */
SELECT SALARIO, SALARIO AS "SALARIO TOTAL" FROM empleados WHERE COMISION IS NULL ORDER BY NUM_EMPLEADO;

/* 15 */
SELECT NUM_EMPLEADO,SALARIO, COMISION, SALARIO+COMISION AS "SALARIO TOTAL" FROM empleados WHERE COMISION IS NOT NULL UNION SELECT NUM_EMPLEADO, SALARIO, SALARIO AS "SALARIO TOTAL" FROM empleados WHERE COMISION IS NULL ORDER BY NUM_EMPLEADO;

/* 16 */
SELECT IF (COMISION IS NOT NULL, `SALARIO`+`COMISION`, `SALARIO`) AS "SALARIO TOTAL" FROM empleados;

/* 17 */
SELECT NOMBRE_EMPLEADO FROM empleados WHERE (SALARIO > 1000 AND NUM_JEFE = 7698);

/* 18 */
SELECT NOMBRE_EMPLEADO FROM empleados WHERE NOT (SALARIO > 1000 AND NUM_JEFE = 7698);

/* 19 */
SELECT `NOMBRE_EMPLEADO`, ((COMISION/(`SALARIO`+ `COMISION`))*100) AS PORCENTAJE FROM `empleados` WHERE COMISION IS NOT NULL AND SALARIO IS NOT NULL ORDER BY NOMBRE_EMPLEADO;

/* 20 */
SELECT NUM_EMPLEADO FROM `empleados` WHERE NUM_DEPARTAMENTO = 10 AND NOMBRE_EMPLEADO NOT LIKE "%LA%";

/* 21 */
SELECT NUM_EMPLEADO FROM `empleados` WHERE NUM_JEFE IS NULL;

/* 22 */
SELECT `NOMBRE_EMPLEADO`, `NUM_DEPARTAMENTO` FROM `empleados` WHERE PUESTO = 'ADMINISTRATIVO' AND NUM_DEPARTAMENTO = 10 AND SALARIO > 800 ORDER BY FECHA_ALTA;

/* 23 */
SELECT * FROM `empleados` WHERE `NOMBRE_EMPLEADO` LIKE "_____";
/* Otra forma */
SELECT * FROM `empleados` WHERE LENGTH(`NOMBRE_EMPLEADO`) = 5;

/* 24 */
SELECT * FROM `empleados` WHERE `NOMBRE_EMPLEADO` LIKE "_____%";
/* Otra forma */
SELECT * FROM `empleados` WHERE LENGTH(`NOMBRE_EMPLEADO`) >= 5;

/* 25 */
SELECT * FROM `empleados` WHERE ((`NOMBRE_EMPLEADO` LIKE "A_" AND SALARIO > 1000) OR (`COMISION` > 0 AND `NUM_DEPARTAMENTO` = 30));

/* 26 */
SELECT `NOMBRE_EMPLEADO`, `SALARIO`+`COMISION` AS SalarioTotal FROM `empleados` WHERE COMISION IS NOT NULL ORDER BY SalarioTotal;

/* 27 */
SELECT `NOMBRE_EMPLEADO`, `SALARIO` AS "SALARIO ACTUAL", `SALARIO` * 1.06 AS "SALARIO FUTURO", IF(COMISION IS NULL, "NO", "SÍ") AS "TIENE COMISIÓN" FROM `empleados`;

/* 28 */
SELECT * FROM `empleados` WHERE `NUM_EMPLEADO` IN (7844, 7900, 7521, 7782, 7934, 7678, 7369);

/* 29 */
SELECT `NUM_EMPLEADO` FROM `empleados` WHERE (`NUM_JEFE`>`NUM_EMPLEADO` AND (SALARIO BETWEEN 1000 AND 2000 OR NUM_DEPARTAMENTO = 30));

/* 30 */
SELECT MAX(`SALARIO`) AS "SALARIO MÁXIMO DE LA EMPRESA", SUM(`COMISION`) AS "TOTAL DESTINADO A COMISIONES", COUNT(`NUM_EMPLEADO`) AS "NÚMERO DE EMPLEADOS" FROM `empleados`;

/* 31 */
SELECT `NOMBRE_EMPLEADO`, `PUESTO`, `SALARIO` FROM `empleados` WHERE SALARIO >= (SELECT `SALARIO` FROM empleados WHERE NOMBRE_EMPLEADO="ALLEN"); /* Puede haber varios empleados apellidados ALLEN en el futuro */

/* 32 */
/* Se resuelve ordenando descendentemente por nombre de empleado y limitando la consulta a 1 resultado */
SELECT NOMBRE_EMPLEADO FROM `empleados` ORDER BY NOMBRE_EMPLEADO DESC LIMIT 1;

/* 33 */
SELECT MAX(`SALARIO`) AS MayorSalario, MIN(`SALARIO`) AS MenorSalario, (MAX(`SALARIO`) - MIN(`SALARIO`)) AS "DIFERENCIA ENTRE EL SALARIO MAYOR Y EL MENOR" FROM `empleados`;

/* 34 */
SELECT `NUM_EMPLEADO`, `NOMBRE_EMPLEADO`, `SALARIO` FROM `empleados` WHERE `SALARIO` = (SELECT MAX(`SALARIO`) FROM `empleados`) OR `SALARIO`= (SELECT MIN(`SALARIO`) FROM `empleados`);

/* 35 */
SELECT NUM_DEPARTAMENTO, AVG(SALARIO) FROM empleados WHERE SALARIO < 5000 GROUP BY `NUM_DEPARTAMENTO` HAVING AVG(SALARIO) > 900;

/* 36 */
SELECT `NUM_EMPLEADO` FROM `empleados` WHERE `SALARIO` >= (SELECT AVG(`SALARIO`) FROM `empleados`);

/* 37 */
SELECT * FROM `empleados` AS emp_padre WHERE SALARIO >=ALL (SELECT SALARIO FROM empleados WHERE NUM_DEPARTAMENTO=emp_padre.`NUM_DEPARTAMENTO`);

/* 38 */
SELECT COUNT(NUM_EMPLEADO) AS "NÚMERO DE EMPLEADOS CON COMISIÓN" FROM `empleados` WHERE COMISION IS NOT NULL;

/* 39 */
SELECT `NUM_DEPARTAMENTO`, COUNT(`NUM_EMPLEADO`) AS "NÚMERO DE EMPLEADOS" FROM empleados GROUP BY NUM_DEPARTAMENTO HAVING COUNT(NUM_EMPLEADO) > 3;

/* 40 */
SELECT NUM_EMPLEADO FROM `empleados` WHERE `NUM_DEPARTAMENTO` = 10 AND SALARIO = ANY (SELECT SALARIO FROM empleados WHERE NUM_DEPARTAMENTO = 20);

/* 41 */
SELECT * FROM `departamentos` WHERE NOT EXISTS (SELECT * from empleados WHERE NUM_DEPARTAMENTO = departamentos.NUM_DEPARTAMENTO);

/* 42 */
SELECT * FROM `empleados` AS emp WHERE (SELECT NUM_DEPARTAMENTO FROM departamentos WHERE NUM_DEPARTAMENTO=emp.NUM_DEPARTAMENTO AND `localidad` IN ("DALLAS", "NEW YORK"));

/* 43 */
SELECT NUM_DEPARTAMENTO as Departamento, SUM(SALARIO) AS Suma FROM empleados GROUP BY NUM_DEPARTAMENTO ORDER BY Suma DESC LIMIT 1;


















